project_id = "pratyusha-mangalagiri"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "5MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:4200"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = false
enable_anonymous_sign_ins = false

[analytics]
enabled = false
