import { PublicPageCopy, SupportedLanguage } from './public-content.model';

export const PUBLIC_CONTENT: Readonly<Record<SupportedLanguage, PublicPageCopy>> = {
  en: {
    locale: 'en',
    brandTagline: 'CLARITY · PRESENCE · GROWTH',
    announcement: 'A thoughtful first conversation about your business',
    announcementCta: 'Start a conversation',
    announcementClose: 'Close announcement',
    navLabel: 'Primary navigation',
    mobileNavLabel: 'Mobile navigation',
    nav: [
      { label: 'Home', href: '#home' },
      { label: 'About', href: '#about' },
      { label: 'Services', href: '#services' },
      { label: 'Benefits', href: '#benefits' },
      { label: 'FAQs', href: '#faq' },
      { label: 'Contact', href: '#contact' },
    ],
    headerCta: 'Let’s talk',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    mobileNote: 'Let’s turn your idea into a clear, credible, and memorable brand.',
    languageLabel: 'Choose website language',
    englishSwitchLabel: 'English selected',
    teluguSwitchLabel: 'Switch website language to Telugu',
    studioLabel: 'BILINGUAL BUSINESS GROWTH STUDIO',
    heroLine1: 'Give your idea',
    heroEmphasis1: 'a clear expression.',
    heroLine2: 'Give your business',
    heroEmphasis2: 'room to grow.',
    heroLede:
      'A thoughtful partnership that understands your story and presents your brand with clarity, beauty, and confidence.',
    heroPrimary: 'Begin a conversation',
    heroSecondary: 'Discover our approach',
    heroAlt: 'Professional portrait of the founder in an elegant traditional saree',
    heroNoteTitle: 'Clarity before creativity.',
    heroNote: 'Every memorable brand begins with a clear understanding of what it stands for.',
    trustLabel: 'What makes our approach different',
    trustItems: [
      {
        number: '01',
        title: 'Personalised guidance',
        text: 'We begin by understanding your story',
      },
      {
        number: '02',
        title: 'Bilingual communication',
        text: 'Clear Telugu and English communication',
      },
      { number: '03', title: 'Goal-led strategy', text: 'A strategy shaped around your goals' },
      {
        number: '04',
        title: 'Meaningful progress',
        text: 'A partnership focused on meaningful progress',
      },
    ],
    problemEyebrow: 'Does this feel familiar?',
    problemTitle: 'You know your business has potential.',
    problemEmphasis: 'But is the direction clear?',
    problemIntro:
      'A strong business needs more than a good idea. Its value must be communicated clearly to the right people.',
    problems: [
      'You have a strong idea, but struggle to express it clearly.',
      'Your online presence does not reflect the quality of your work.',
      'Your efforts are not consistently reaching the right customers.',
      'You are unsure what to prioritise now and what should come next.',
    ],
    problemBridge: 'You do not need to figure out everything alone.',
    problemBridgeStrong: 'You need a thoughtful partner who can help clarify the way forward.',
    solutionEyebrow: 'Our perspective',
    solutionTitle: 'It should not only look beautiful.',
    solutionEmphasis: 'It should work with purpose.',
    solutionBody:
      'We bring together your business intent, your customers’ needs, and your distinct point of view to create a brand experience that builds trust.',
    solutionQuote:
      'Design without strategy is decoration. Design guided by clarity becomes a foundation for growth.',
    servicesEyebrow: 'Support for your growth journey',
    servicesTitle: 'Clear support for',
    servicesEmphasis: 'every meaningful stage',
    servicesIntro: 'No unnecessary complexity—only focused work that moves your business forward.',
    services: [
      {
        number: '01',
        title: 'Brand Clarity',
        text: 'Define who your business serves, what makes it distinct, and how it should be remembered.',
      },
      {
        number: '02',
        title: 'Digital Presence',
        text: 'Build a website and digital experience that presents your value with confidence and care.',
      },
      {
        number: '03',
        title: 'Growth Strategy',
        text: 'Create a practical growth plan aligned with your current stage, goals, and resources.',
      },
    ],
    benefitEyebrow: 'What you gain',
    benefitTitle: 'More than',
    benefitEmphasis: 'a website.',
    benefitIntro:
      'Clarity behind every decision. Purpose behind every design. Your growth behind every step.',
    benefits: [
      {
        number: '01',
        title: 'A clear direction',
        text: 'Confidence about what to prioritise, what to postpone, and why.',
      },
      {
        number: '02',
        title: 'A brand that earns trust',
        text: 'A professional experience from the very first customer interaction.',
      },
      {
        number: '03',
        title: 'Connection with the right audience',
        text: 'Communication that helps ideal customers understand your value.',
      },
      {
        number: '04',
        title: 'A foundation for steady growth',
        text: 'A useful long-term system rather than a one-time promotional effort.',
      },
    ],
    processEyebrow: 'How we work together',
    processTitle: 'From uncertainty to',
    processEmphasis: 'a clear next step.',
    process: [
      {
        number: '01',
        title: 'Listen',
        text: 'We understand your journey, present challenges, and the goal you want to reach.',
      },
      {
        number: '02',
        title: 'Clarify',
        text: 'We identify priorities and shape a direction that is right for your business.',
      },
      {
        number: '03',
        title: 'Build',
        text: 'We turn the strategy into a clear, beautiful, and useful digital experience.',
      },
      {
        number: '04',
        title: 'Refine',
        text: 'We observe results and improve what matters as your business moves forward.',
      },
    ],
    aboutEyebrow: 'About Pratyusha',
    aboutTitle: 'A partner who sees',
    aboutEmphasis: 'your business as you do.',
    aboutBody1:
      'Every business begins with a personal story. We listen carefully, recognise the value within it, and help present it to the world with confidence.',
    aboutBody2:
      'We believe in thoughtful ideas and beautiful execution shaped around your reality—not grand promises or one-size-fits-all solutions.',
    aboutValues: ['Care', 'Clarity', 'Integrity', 'Quality'],
    aboutBadge: 'YOUR GROWTH PARTNER',
    testimonialsEyebrow: 'Stories of progress',
    testimonialsTitle: 'Meaningful changes',
    testimonialsEmphasis: 'that began with trust',
    testimonialsPending: 'Client-approved testimonials will appear here after review.',
    faqEyebrow: 'Frequently asked questions',
    faqTitle: 'Helpful answers to',
    faqEmphasis: 'the questions on your mind',
    faqPrompt: 'Still have a question?',
    faqLink: 'Talk to us directly.',
    faqs: [
      {
        question: 'Who is this service for?',
        answer:
          'It is designed for new founders, established small businesses improving their digital presence, and business owners who want a clearer brand direction.',
      },
      {
        question: 'How long does the process take?',
        answer:
          'Timing depends on the scope and your needs. After the initial conversation, we share clear stages, an estimated timeline, and what is required from both sides.',
      },
      {
        question: 'Can we communicate in Telugu?',
        answer: 'Yes. We can work in Telugu, English, or a comfortable combination of both.',
      },
      {
        question: 'What happens in the first conversation?',
        answer:
          'We discuss your present situation, primary challenge, and goal. You leave with clarity about whether we are a good fit and the most useful next step.',
      },
      {
        question: 'How is pricing decided?',
        answer:
          'One package cannot serve every business. Once we understand the work you genuinely need, we share a transparent proposal and cost.',
      },
    ],
    conversionEyebrow: 'Your next step',
    conversionTitle: 'Let’s talk about your idea.',
    conversionEmphasis: 'And see where it can go.',
    conversionBody:
      'A relaxed first conversation to understand your situation and identify a useful next step—without pressure.',
    conversionCta: 'Start the conversation',
    contactEyebrow: 'Contact',
    contactTitle: 'We are ready',
    contactEmphasis: 'to hear your story.',
    contactBody:
      'Share a few details below. We will understand your requirement and usually respond within one or two working days.',
    locationLabel: 'BASED IN',
    location: 'Hyderabad · Serving Worldwide',
    contactNote: 'Contact details will be updated after receiving final client information.',
    form: {
      heading: 'Your details',
      name: 'Full Name',
      namePlaceholder: 'Your full name',
      mobile: 'Mobile Number',
      mobilePlaceholder: '10-digit mobile number',
      email: 'Email Address',
      emailPlaceholder: 'name@example.com',
      city: 'City',
      cityPlaceholder: 'Your city',
      requirement: 'Requirement',
      requirementPlaceholder: 'Choose an option',
      requirementOptions: [
        ['brand', 'Brand clarity'],
        ['website', 'Website / digital presence'],
        ['growth', 'Growth strategy'],
        ['other', 'Other requirement'],
      ],
      message: 'Message',
      messagePlaceholder: 'Tell us briefly about your business, current challenge, and goal...',
      consent: 'I agree that my details may be used to respond to this enquiry.',
      submit: 'Submit enquiry',
      optional: 'Optional',
      privacy: 'Your information stays private. This Step 3 preview does not send or store it.',
      required: 'Please complete this required field.',
      mobileInvalid: 'Enter a valid 10-digit Indian mobile number.',
      emailInvalid: 'Enter a valid email address.',
      maxLength: 'Please shorten this response.',
      developmentNotice: 'Preview only. Your details were not sent or stored.',
    },
    footerStatement: 'Clarity for your idea. Distinction for your brand. Growth for your business.',
    footerNavigation: 'Navigation',
    footerLegal: 'Legal',
    footerRights: 'All rights reserved.',
    backToTop: 'Back to top',
    skipLink: 'Skip to main content',
    cookieTitle: 'Your privacy matters',
    cookieBody: 'We use only essential storage for a reliable bilingual experience.',
    cookieAccept: 'Accept',
    cookieSettings: 'Preferences',
  },
  te: {
    locale: 'te',
    brandTagline: 'CLARITY · PRESENCE · GROWTH',
    announcement: 'మీ వ్యాపారం గురించి శ్రద్ధతో కూడిన తొలి సంభాషణ',
    announcementCta: 'సంభాషణ ప్రారంభించండి',
    announcementClose: 'ప్రకటనను మూసివేయండి',
    navLabel: 'ప్రధాన నావిగేషన్',
    mobileNavLabel: 'మొబైల్ నావిగేషన్',
    nav: [
      { label: 'హోమ్', href: '#home' },
      { label: 'మా గురించి', href: '#about' },
      { label: 'మా సేవలు', href: '#services' },
      { label: 'ప్రయోజనాలు', href: '#benefits' },
      { label: 'ప్రశ్నలు', href: '#faq' },
      { label: 'సంప్రదించండి', href: '#contact' },
    ],
    headerCta: 'మాట్లాడదాం',
    openMenu: 'మెనూ తెరవండి',
    closeMenu: 'మెనూ మూసివేయండి',
    mobileNote: 'మీ ఆలోచనను అందమైన, నమ్మకమైన బ్రాండ్‌గా మార్చుకుందాం.',
    languageLabel: 'వెబ్‌సైట్ భాషను ఎంచుకోండి',
    englishSwitchLabel: 'వెబ్‌సైట్ భాషను ఆంగ్లంలోకి మార్చండి',
    teluguSwitchLabel: 'తెలుగు ఎంపిక చేయబడింది',
    studioLabel: 'TELUGU BUSINESS GROWTH STUDIO',
    heroLine1: 'మీ ఆలోచనకు',
    heroEmphasis1: 'సరైన రూపం.',
    heroLine2: 'మీ వ్యాపారానికి',
    heroEmphasis2: 'స్థిరమైన ఎదుగుదల.',
    heroLede:
      'మీ కథను అర్థం చేసుకుని, మీ బ్రాండ్‌ను స్పష్టంగా, అందంగా, నమ్మకంగా ప్రపంచానికి పరిచయం చేసే భాగస్వామ్యం.',
    heroPrimary: 'సంభాషణ ప్రారంభిద్దాం',
    heroSecondary: 'మా విధానం తెలుసుకోండి',
    heroAlt: 'సాంప్రదాయ చీరలో సంస్థ వ్యవస్థాపకురాలి వృత్తిపరమైన చిత్రం',
    heroNoteTitle: 'Clarity before creativity.',
    heroNote: 'ప్రతి అందమైన బ్రాండ్ వెనుక ఒక స్పష్టమైన ఆలోచన ఉంటుంది.',
    trustLabel: 'మా ప్రత్యేకతలు',
    trustItems: [
      { number: '01', title: 'వ్యక్తిగత మార్గదర్శనం', text: 'మీ కథను అర్థం చేసుకునే విధానం' },
      { number: '02', title: 'ద్విభాషా కమ్యూనికేషన్', text: 'తెలుగులో స్పష్టమైన కమ్యూనికేషన్' },
      { number: '03', title: 'లక్ష్యానికి తగిన వ్యూహం', text: 'మీ లక్ష్యానికి సరిపోయే వ్యూహం' },
      { number: '04', title: 'అర్థవంతమైన పురోగతి', text: 'ఫలితాలపై దృష్టి పెట్టే భాగస్వామ్యం' },
    ],
    problemEyebrow: 'ఇది మీకు పరిచయంగా అనిపిస్తుందా?',
    problemTitle: 'మీలో సామర్థ్యం ఉంది.',
    problemEmphasis: 'కానీ స్పష్టత లేదా?',
    problemIntro:
      'మంచి వ్యాపారం ఉండటం ఒక్కటే సరిపోదు. దాని విలువను సరైన వ్యక్తులకు సరైన విధంగా చూపించగలగాలి.',
    problems: [
      'మంచి ఆలోచన ఉన్నా, దాన్ని స్పష్టంగా ఎలా చెప్పాలో తెలియకపోవడం',
      'ఆన్‌లైన్‌లో మీ వ్యాపారం ప్రొఫెషనల్‌గా కనిపించకపోవడం',
      'ఎన్నో ప్రయత్నాలు చేసినా సరైన కస్టమర్లను చేరుకోలేకపోవడం',
      'ఎక్కడ మొదలు పెట్టాలి, తర్వాత ఏం చేయాలి అనే గందరగోళం',
    ],
    problemBridge: 'మీరు ఒంటరిగా అన్నీ తెలుసుకోవాల్సిన అవసరం లేదు.',
    problemBridgeStrong: 'మీకు కావాల్సింది—సరైన దిశ చూపించే భాగస్వామి.',
    solutionEyebrow: 'మా దృక్పథం',
    solutionTitle: 'అందంగా కనిపించడం మాత్రమే కాదు.',
    solutionEmphasis: 'అర్థవంతంగా పనిచేయాలి.',
    solutionBody:
      'మీ వ్యాపారం వెనుక ఉన్న ఉద్దేశాన్ని, మీ కస్టమర్ల అవసరాన్ని, మార్కెట్‌లో మీ ప్రత్యేకతను కలిపి—నమ్మకాన్ని పెంచే బ్రాండ్ అనుభవాన్ని నిర్మిస్తాం.',
    solutionQuote: 'వ్యూహం లేని డిజైన్ అలంకరణ మాత్రమే. స్పష్టతతో కూడిన డిజైన్ ఎదుగుదలకు పునాది.',
    servicesEyebrow: 'మీ ఎదుగుదల ప్రయాణంలో',
    servicesTitle: 'ప్రతి దశకు',
    servicesEmphasis: 'స్పష్టమైన సహకారం',
    servicesIntro: 'మీకు అవసరం లేని సంక్లిష్టత లేకుండా, అవసరమైన దానిపై దృష్టి.',
    services: [
      {
        number: '01',
        title: 'బ్రాండ్ స్పష్టత',
        text: 'మీ వ్యాపారం ఎవరి కోసం, ఎందుకు ప్రత్యేకం, ఎలా గుర్తుండాలి అనే విషయాలకు స్పష్టమైన దిశ.',
      },
      {
        number: '02',
        title: 'డిజిటల్ ప్రెజెన్స్',
        text: 'మీ విలువను నమ్మకంగా చూపించే వెబ్‌సైట్, కంటెంట్ మరియు డిజిటల్ అనుభవానికి పునాది.',
      },
      {
        number: '03',
        title: 'గ్రోత్ వ్యూహం',
        text: 'మీ ప్రస్తుత దశ, లక్ష్యం మరియు వనరులకు సరిపోయే ఆచరణాత్మక ఎదుగుదల ప్రణాళిక.',
      },
    ],
    benefitEyebrow: 'మీరు పొందేది',
    benefitTitle: 'ఒక వెబ్‌సైట్ కంటే',
    benefitEmphasis: 'ఎక్కువ.',
    benefitIntro:
      'ప్రతి నిర్ణయం వెనుక స్పష్టత. ప్రతి డిజైన్ వెనుక ఉద్దేశం. ప్రతి అడుగు వెనుక మీ ఎదుగుదల.',
    benefits: [
      {
        number: '01',
        title: 'స్పష్టమైన దిశ',
        text: 'ఏది ముందుగా చేయాలో, ఏది వేచి ఉండాలో నిర్ణయించగల ఆత్మవిశ్వాసం.',
      },
      {
        number: '02',
        title: 'నమ్మకం కలిగించే బ్రాండ్',
        text: 'మీ కస్టమర్లు చూసిన మొదటి క్షణం నుంచే ప్రొఫెషనల్ అనుభూతి.',
      },
      {
        number: '03',
        title: 'సరైన కస్టమర్లతో అనుసంధానం',
        text: 'మీ సేవ విలువను అర్థం చేసుకునే వ్యక్తులను చేరుకునే కమ్యూనికేషన్.',
      },
      {
        number: '04',
        title: 'స్థిరంగా ఎదిగే వ్యవస్థ',
        text: 'ఒక్కసారి చేసే ప్రచారం కాకుండా, దీర్ఘకాలానికి ఉపయోగపడే పునాది.',
      },
    ],
    processEyebrow: 'మనం కలిసి ఎలా పనిచేస్తాం',
    processTitle: 'గందరగోళం నుంచి',
    processEmphasis: 'స్పష్టమైన ముందడుగుకు.',
    process: [
      {
        number: '01',
        title: 'వింటాం',
        text: 'మీ ప్రయాణం, ప్రస్తుతం ఉన్న సవాళ్లు, మీరు చేరాలనుకునే లక్ష్యాన్ని అర్థం చేసుకుంటాం.',
      },
      {
        number: '02',
        title: 'స్పష్టం చేస్తాం',
        text: 'అవసరమైన ప్రాధాన్యతలను గుర్తించి, మీకు సరిపోయే దిశను రూపొందిస్తాం.',
      },
      {
        number: '03',
        title: 'నిర్మిస్తాం',
        text: 'వ్యూహాన్ని అందమైన, సులభమైన మరియు ఉపయోగకరమైన డిజిటల్ అనుభవంగా మారుస్తాం.',
      },
      {
        number: '04',
        title: 'మెరుగుపరుస్తాం',
        text: 'ఫలితాలను గమనించి, అవసరమైన చోట మెరుగుపరుస్తూ ముందుకు సాగుతాం.',
      },
    ],
    aboutEyebrow: 'Pratyusha గురించి',
    aboutTitle: 'మీ వ్యాపారాన్ని',
    aboutEmphasis: 'మీలా చూసే భాగస్వామి.',
    aboutBody1:
      'ప్రతి వ్యాపారం వెనుక ఒక వ్యక్తిగత కథ ఉంటుంది. ఆ కథను శ్రద్ధగా విని, అందులోని విలువను గుర్తించి, ప్రపంచానికి నమ్మకంగా చూపించడమే మా పని.',
    aboutBody2:
      'పెద్ద మాటలు, ఒకేలా ఉండే పరిష్కారాలకంటే—మీ పరిస్థితికి సరిపోయే స్పష్టమైన ఆలోచనలను, అందమైన అమలును మేము నమ్ముతాం.',
    aboutValues: ['శ్రద్ధ', 'స్పష్టత', 'నిజాయితీ', 'నాణ్యత'],
    aboutBadge: 'YOUR GROWTH PARTNER',
    testimonialsEyebrow: 'కలిసి ఎదిగిన కథలు',
    testimonialsTitle: 'నమ్మకం నుంచి మొదలైన',
    testimonialsEmphasis: 'అందమైన మార్పులు',
    testimonialsPending: 'క్లయింట్ ఆమోదించిన టెస్టిమోనియల్స్ సమీక్ష తర్వాత ఇక్కడ కనిపిస్తాయి.',
    faqEyebrow: 'సాధారణ ప్రశ్నలు',
    faqTitle: 'మీ మనసులో ఉన్న',
    faqEmphasis: 'ప్రశ్నలకు సమాధానాలు',
    faqPrompt: 'మీ ప్రశ్న ఇక్కడ కనిపించలేదా?',
    faqLink: 'మాతో నేరుగా మాట్లాడండి.',
    faqs: [
      {
        question: 'ఈ సేవ ఎవరికీ సరిపోతుంది?',
        answer:
          'కొత్తగా వ్యాపారం మొదలు పెడుతున్నవారు, ఇప్పటికే వ్యాపారం ఉన్నా ఆన్‌లైన్ ప్రెజెన్స్‌ను మెరుగుపరచాలనుకునేవారు, తమ బ్రాండ్‌కు స్పష్టమైన దిశ కావాలనుకునేవారికి ఈ సేవ ఉపయోగపడుతుంది.',
      },
      {
        question: 'ప్రక్రియ ఎంత సమయం పడుతుంది?',
        answer:
          'మీ అవసరాలు, పనివ్యాప్తిని బట్టి సమయం మారుతుంది. ప్రారంభ సంభాషణ తర్వాత దశలు, అంచనా సమయం, అవసరమైన వివరాలను పారదర్శకంగా పంచుకుంటాం.',
      },
      {
        question: 'తెలుగులోనే మొత్తం చర్చించవచ్చా?',
        answer:
          'అవును. మీకు సౌకర్యమైన విధంగా తెలుగులో లేదా అవసరాన్ని బట్టి తెలుగు–English కలిపి కమ్యూనికేట్ చేయవచ్చు.',
      },
      {
        question: 'మొదటి సంభాషణలో ఏమి జరుగుతుంది?',
        answer:
          'మీ ప్రస్తుత పరిస్థితి, ప్రధాన సవాలు, లక్ష్యం గురించి మాట్లాడుతాం. కలిసి పనిచేయడం సరిపోతుందా, తదుపరి సరైన అడుగు ఏంటి అనే స్పష్టతతో ముగిస్తాం.',
      },
      {
        question: 'ధరలు ఎలా నిర్ణయిస్తారు?',
        answer:
          'ఒకే ప్యాకేజ్ అందరికీ సరిపోదు. మీకు నిజంగా అవసరమైన పనిని అర్థం చేసుకున్న తర్వాత స్పష్టమైన ప్రతిపాదన మరియు ఖర్చును ముందుగానే అందిస్తాం.',
      },
    ],
    conversionEyebrow: 'మీ తదుపరి అడుగు',
    conversionTitle: 'మీ ఆలోచన గురించి మాట్లాడదాం.',
    conversionEmphasis: 'అది ఎక్కడికి వెళ్లగలదో చూద్దాం.',
    conversionBody:
      'ఎలాంటి ఒత్తిడి లేదు. మీ ప్రస్తుత పరిస్థితిని అర్థం చేసుకుని, తదుపరి సరైన అడుగును కలిసి గుర్తించే పరిచయ సంభాషణ.',
    conversionCta: 'సంభాషణ ప్రారంభిద్దాం',
    contactEyebrow: 'సంప్రదించండి',
    contactTitle: 'మీ కథను',
    contactEmphasis: 'వినడానికి సిద్ధంగా ఉన్నాం.',
    contactBody:
      'ఈ చిన్న ఫారమ్‌లో వివరాలు పంచుకోండి. మీ అవసరాన్ని అర్థం చేసుకుని, సాధారణంగా 1–2 పనిదినాల్లో స్పందిస్తాం.',
    locationLabel: 'BASED IN',
    location: 'Hyderabad · Serving Worldwide',
    contactNote: 'సంప్రదింపు వివరాలు క్లయింట్ నుంచి వచ్చిన తర్వాత అప్‌డేట్ అవుతాయి.',
    form: {
      heading: 'మీ వివరాలు',
      name: 'పూర్తి పేరు',
      namePlaceholder: 'మీ పూర్తి పేరు',
      mobile: 'మొబైల్ నంబర్',
      mobilePlaceholder: '10 అంకెల మొబైల్ నంబర్',
      email: 'ఇమెయిల్ చిరునామా',
      emailPlaceholder: 'name@example.com',
      city: 'నగరం',
      cityPlaceholder: 'మీ నగరం',
      requirement: 'మీ అవసరం',
      requirementPlaceholder: 'ఒక ఎంపికను ఎంచుకోండి',
      requirementOptions: [
        ['brand', 'బ్రాండ్ స్పష్టత'],
        ['website', 'వెబ్‌సైట్ / డిజిటల్ ప్రెజెన్స్'],
        ['growth', 'గ్రోత్ వ్యూహం'],
        ['other', 'ఇతర అవసరం'],
      ],
      message: 'సందేశం',
      messagePlaceholder: 'మీ వ్యాపారం, ప్రస్తుత సవాలు, మీ లక్ష్యం...',
      consent: 'నా వివరాలను ఈ విచారణకు స్పందించేందుకు ఉపయోగించడానికి అంగీకరిస్తున్నాను.',
      submit: 'విచారణను పంపండి',
      optional: 'ఐచ్ఛికం',
      privacy: 'మీ సమాచారం గోప్యంగా ఉంటుంది. ఈ Step 3 ప్రివ్యూ దాన్ని పంపదు లేదా సేవ్ చేయదు.',
      required: 'దయచేసి ఈ తప్పనిసరి వివరాన్ని నమోదు చేయండి.',
      mobileInvalid: 'చెల్లుబాటు అయ్యే 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి.',
      emailInvalid: 'చెల్లుబాటు అయ్యే ఇమెయిల్ చిరునామా నమోదు చేయండి.',
      maxLength: 'దయచేసి ఈ సమాధానాన్ని కొంచెం కుదించండి.',
      developmentNotice: 'ఇది ప్రివ్యూ మాత్రమే. మీ వివరాలు పంపబడలేదు లేదా సేవ్ చేయబడలేదు.',
    },
    footerStatement: 'మీ ఆలోచనకు స్పష్టత. మీ బ్రాండ్‌కు ప్రత్యేకత. మీ వ్యాపారానికి ఎదుగుదల.',
    footerNavigation: 'నావిగేషన్',
    footerLegal: 'చట్టపరమైనవి',
    footerRights: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    backToTop: 'పేజీ పైకి వెళ్లండి',
    skipLink: 'ప్రధాన కంటెంట్‌కు వెళ్లండి',
    cookieTitle: 'మీ గోప్యత ముఖ్యం',
    cookieBody: 'నమ్మకమైన ద్విభాషా అనుభవం కోసం అవసరమైన స్టోరేజ్‌ను మాత్రమే ఉపయోగిస్తాం.',
    cookieAccept: 'అంగీకరించండి',
    cookieSettings: 'ఎంపికలు',
  },
};
