import { ProductMedia, PublicPageCopy, SupportedLanguage } from './public-content.model';

const PRODUCT_MEDIA: Readonly<
  Record<'success' | 'evilEye' | 'moneyMagnet' | 'pyrite', ProductMedia>
> = {
  success: {
    imageUrl: 'assets/images/products/success-bracelet.webp',
    imageSrcSet:
      'assets/images/products/success-bracelet-640.webp 640w, assets/images/products/success-bracelet.webp 700w',
    imageAltEn: 'Multicoloured crystal Success Bracelet displayed in a hand',
    imageAltTe: 'చేతిలో చూపించిన వివిధ రంగుల క్రిస్టల్ సక్సెస్ బ్రేస్‌లెట్',
    imageWidth: 700,
    imageHeight: 700,
    imageFocalX: 50,
    imageFocalY: 50,
    imageStatus: 'approved',
  },
  evilEye: {
    imageUrl: 'assets/images/products/evil-eye-protection-bracelet.webp',
    imageSrcSet:
      'assets/images/products/evil-eye-protection-bracelet-640.webp 640w, assets/images/products/evil-eye-protection-bracelet.webp 660w',
    imageAltEn: 'Blue, black and white crystal Evil Eye Protection Bracelet displayed in a hand',
    imageAltTe: 'చేతిలో చూపించిన నీలం, నలుపు మరియు తెలుపు రంగుల ఈవిల్ ఐ ప్రొటెక్షన్ బ్రేస్‌లెట్',
    imageWidth: 660,
    imageHeight: 660,
    imageFocalX: 50,
    imageFocalY: 50,
    imageStatus: 'approved',
  },
  moneyMagnet: {
    imageUrl: 'assets/images/products/money-magnet-bracelet.webp',
    imageSrcSet:
      'assets/images/products/money-magnet-bracelet-640.webp 640w, assets/images/products/money-magnet-bracelet.webp 650w',
    imageAltEn: 'Mixed crystal Money Magnet Bracelet with yellow and dark beads',
    imageAltTe: 'పసుపు మరియు ముదురు రంగు పూసలతో ఉన్న మనీ మ్యాగ్నెట్ బ్రేస్‌లెట్',
    imageWidth: 650,
    imageHeight: 650,
    imageFocalX: 50,
    imageFocalY: 50,
    imageStatus: 'approved',
  },
  pyrite: {
    imageUrl: 'assets/images/products/pyrite-bracelet.webp',
    imageSrcSet:
      'assets/images/products/pyrite-bracelet-640.webp 640w, assets/images/products/pyrite-bracelet.webp 670w',
    imageAltEn: 'Metallic gold-tone Pyrite Bracelet displayed in a hand',
    imageAltTe: 'చేతిలో చూపించిన మెటాలిక్ గోల్డ్ రంగు పైరైట్ బ్రేస్‌లెట్',
    imageWidth: 670,
    imageHeight: 670,
    imageFocalX: 50,
    imageFocalY: 50,
    imageStatus: 'approved',
  },
};

export const PUBLIC_CONTENT: Readonly<Record<SupportedLanguage, PublicPageCopy>> = {
  en: {
    locale: 'en',
    brandTagline: 'CRYSTALS · INTENTION · PRACTICE',
    announcement: 'A complimentary 21-Day Crystal Ritual with every eligible bracelet purchase.',
    announcementCta: 'Explore the experience',
    announcementClose: 'Close announcement',
    navLabel: 'Primary navigation',
    mobileNavLabel: 'Mobile navigation',
    nav: [
      { label: 'Home', href: '#home' },
      { label: 'Collection', href: '#collection' },
      { label: '21-Day Ritual', href: '#ritual' },
      { label: 'About', href: '#about' },
      { label: 'FAQs', href: '#faq' },
      { label: 'Contact', href: '#contact' },
    ],
    headerCta: 'Explore collection',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    mobileNote: 'Choose an intention, explore the collection, and ask before you decide.',
    languageLabel: 'Choose website language',
    englishSwitchLabel: 'English selected',
    teluguSwitchLabel: 'Switch website language to Telugu',
    studioLabel: 'A PERSONAL CRYSTAL EXPERIENCE',
    heroTitle: 'Transform Your Energy.',
    heroEmphasis: 'Transform Your Life.',
    heroSupporting:
      'Handpicked crystal bracelets with personal guidance and a complimentary 21-Day Crystal Ritual focused on mindfulness, intention-setting, affirmations, and consistent personal action.',
    heroBody:
      'Choose a bracelet that reflects the intention you want to practise. Then use it as a daily reminder while following a simple, guided 21-day routine.',
    heroPrimary: 'Explore the Crystal Collection',
    heroSecondary: 'Learn About the 21-Day Ritual',
    differentiatorTitle: 'A More Personal Crystal Experience',
    differentiatorSupporting: 'Guidance beyond the bracelet.',
    differentiatorBody:
      'The experience is designed around a bracelet, a chosen intention, and a consistent personal practice.',
    differentiators: [
      'Bracelets selected with care',
      'Personal guidance from Pratyusha',
      'A complimentary 21-day practice',
      'Mindfulness, positive habits, and practical action',
    ],
    challenge: {
      eyebrow: 'A familiar challenge',
      title: 'When Your Intentions Are Clear but Consistency Feels Difficult',
      supporting: 'A small daily reminder can help you return to what matters.',
      body: 'Busy routines, competing priorities, and moments of self-doubt can make it difficult to stay connected to personal or professional goals. A simple practice can create space to pause, reflect, and choose the next practical step.',
      bullets: [],
    },
    support: {
      eyebrow: 'Crystal-practice support',
      title: 'A Daily Reminder for Your Intentions',
      supporting:
        'Crystal practices are intended to complement mindfulness, reflection, and personal action.',
      body: 'A bracelet can serve as a visual cue to pause, remember your intention, and return to the habits you want to practise. It does not create a guaranteed result; the value comes from how consistently you combine reflection with practical action.',
      bullets: [
        'Supports intention-setting',
        'Encourages positive habits',
        'May help you stay focused on chosen goals',
        'Can complement a regular mindfulness or self-care practice',
      ],
    },
    collection: {
      eyebrow: 'Signature collection',
      title: 'The Signature Crystal Collection',
      supporting: 'Choose a bracelet that reflects the intention you want to practise.',
      body: 'Each bracelet is presented as a symbolic reminder that can accompany mindfulness, positive habits, and consistent personal action. Individual experiences may vary.',
      bullets: [],
    },
    products: [
      {
        id: 'success',
        nameEn: 'Success Bracelet',
        nameTe: 'సక్సెస్ బ్రేస్‌లెట్',
        supporting:
          'A daily reminder to stay connected to your goals and the actions that support them.',
        body: 'Designed for people who want to practise confidence, motivation, goal focus, and a positive mindset. It may help you remember your intention; it does not guarantee career, business, academic, or personal success.',
        points: ['Confidence', 'Motivation', 'Goal focus', 'Positive habits'],
        cta: 'Enquire About the Success Bracelet',
        ...PRODUCT_MEDIA.success,
      },
      {
        id: 'evil-eye',
        nameEn: 'Evil Eye Protection Bracelet',
        nameTe: 'ఈవిల్ ఐ ప్రొటెక్షన్ బ్రేస్‌లెట్',
        supporting:
          'A traditional symbol and a personal reminder of calm, positive boundaries, and daily confidence.',
        body: 'For people who connect with the Evil Eye symbol and want a visual cue for mindful boundaries and inner calm. The name reflects a traditional association; it does not assure protection from people, events, energy, or harm.',
        points: ['Emotional balance', 'Calmness', 'Positive boundaries', 'Personal confidence'],
        cta: 'Enquire About the Evil Eye Bracelet',
        ...PRODUCT_MEDIA.evilEye,
      },
      {
        id: 'money-magnet',
        nameEn: 'Money Magnet Bracelet',
        nameTe: 'మనీ మ్యాగ్నెట్ బ్రేస్‌లెట్',
        supporting:
          'A reminder to strengthen an abundance mindset and stay focused on practical financial goals.',
        body: 'Designed for adults who want to practise opportunity awareness, intentional financial habits, and consistent action. It does not promise wealth, income, investment performance, or business success.',
        points: [
          'Abundance mindset',
          'Opportunity awareness',
          'Financial intention-setting',
          'Positive financial habits',
        ],
        cta: 'Enquire About the Money Magnet Bracelet',
        ...PRODUCT_MEDIA.moneyMagnet,
      },
      {
        id: 'pyrite',
        nameEn: 'Pyrite Bracelet',
        nameTe: 'పైరైట్ బ్రేస్‌లెట్',
        supporting:
          'Traditionally associated with confidence and prosperity, and used here as a reminder to stay action-oriented.',
        body: 'Designed for entrepreneurs and professionals who want a visible cue for confidence, motivation, leadership, and productive action. Traditional associations are belief-based and do not guarantee prosperity or professional results.',
        points: ['Confidence', 'Motivation', 'Leadership mindset', 'Productivity'],
        cta: 'Enquire About the Pyrite Bracelet',
        ...PRODUCT_MEDIA.pyrite,
      },
    ],
    ritual: {
      eyebrow: 'Complimentary 21-Day Crystal Ritual',
      title: 'Guidance Beyond the Bracelet',
      supporting:
        'A 21-day practice focused on mindfulness, intention-setting, affirmations, gratitude, and consistent personal action.',
      body: 'The proposed ritual is designed to help you build a simple daily routine around your chosen intention.',
      bullets: [
        'Pause and reconnect with your chosen intention',
        'Use affirmations and reflection as mindful prompts',
        'Practise gratitude and positive habits',
        'Pair reflection with consistent personal action',
      ],
    },
    ritualNote:
      'Final inclusions, delivery method, schedule, access, and eligibility will be confirmed before secure ordering is enabled.',
    audience: {
      eyebrow: 'Who it is for',
      title: 'For People Who Want a More Intentional Daily Practice',
      supporting: 'Beginner-friendly and designed to complement practical personal action.',
      body: 'This experience may suit people who want a simple reminder to pause, reflect, and stay connected to positive habits.',
      bullets: [
        'Working professionals and business owners',
        'Entrepreneurs and students',
        'Homemakers',
        'Spiritual seekers',
        'People beginning mindfulness or personal-growth practices',
      ],
    },
    experienceDifference: {
      eyebrow: 'A thoughtful difference',
      title: 'What Makes This Crystal Journey Different',
      supporting: 'A bracelet, a guided routine, and an emphasis on consistent practice.',
      body: 'The intended difference is the support around the bracelet—not a promise that the crystal will produce a fixed outcome.',
      bullets: [
        'A bracelet selected with care',
        'Personal guidance from Pratyusha',
        'A complimentary 21-day practice',
        'Guided intention and affirmation activities',
        'Encouragement to combine reflection with practical action',
      ],
    },
    processEyebrow: 'How it works',
    processTitle: 'Your Crystal Journey',
    processSupporting: 'From choosing an intention to building a consistent practice.',
    process: [
      {
        number: '01',
        title: 'Choose',
        text: 'Explore the collection and identify the intention you want to practise.',
      },
      {
        number: '02',
        title: 'Confirm',
        text: 'Ask questions and use the confirmed enquiry process.',
      },
      {
        number: '03',
        title: 'Receive',
        text: 'Receive your bracelet with the approved care and ritual information.',
      },
      { number: '04', title: 'Practise', text: 'Follow the confirmed 21-day guidance.' },
      {
        number: '05',
        title: 'Continue',
        text: 'Carry useful habits forward through consistent personal action.',
      },
    ],
    aboutEyebrow: 'About Pratyusha',
    aboutTitle: 'Personal Guidance from Pratyusha',
    aboutSupporting: 'A thoughtful approach to crystals, intention, and consistent daily practice.',
    aboutBody:
      'Pratyusha created this experience for people who want more than a bracelet. Her intended role is to help customers choose an intention and follow a structured 21-day practice.',
    aboutBadge: 'PERSONAL GUIDANCE',
    founderAlt: 'Pratyusha wearing a traditional pink saree in a warm indoor setting',
    faqEyebrow: 'Frequently asked questions',
    faqTitle: 'Clear Answers Before You Choose',
    faqSupporting: 'Only details that can be stated safely are shown here.',
    faqPrompt: 'Still have a question?',
    faqLink: 'Send an enquiry.',
    faqs: [
      {
        question: 'Do I need previous spiritual experience?',
        answer:
          'No. The experience is intended to be beginner-friendly. You may approach the bracelet as a personal symbol and the ritual as a simple mindfulness and intention-setting practice.',
      },
      {
        question: 'Can I wear my bracelet every day?',
        answer:
          'Many people use a bracelet as a daily reminder of their intention. Final wear and care guidance depends on the confirmed materials, construction, water exposure, and skin-sensitivity information.',
      },
      {
        question: 'What happens during the 21-Day Ritual?',
        answer:
          'The proposed experience focuses on intention-setting, affirmations, reflection, gratitude, and simple daily practices. Final inclusions and delivery methods will be confirmed before ordering is enabled.',
      },
    ],
    disclaimerTitle: 'A Note About Crystal and Wellness Practices',
    disclaimerBody:
      'Crystal products and the 21-Day Crystal Ritual are intended to complement mindfulness, intention-setting, reflection, and personal-wellness practices. They are not medical treatments and are not substitutes for professional medical, psychological, legal, or financial advice. Individual experiences may vary. No financial, health, relationship, career, business, or protection outcome is guaranteed. Continue to take appropriate practical action and seek qualified professional help where necessary.',
    conversionEyebrow: 'Begin with one intentional step',
    conversionTitle: 'Explore the bracelet that reflects the intention you want to practise.',
    conversionBody:
      'Review the collection, learn about the proposed 21-day experience, and ask any questions before deciding.',
    conversionCta: 'Explore the Crystal Collection',
    contactEyebrow: 'Enquiry',
    contactTitle: 'Ready to Ask About a Bracelet?',
    contactSupporting: 'Share the bracelet name, your city, and your question.',
    contactBody:
      'Secure submission will be enabled during backend integration. Prices, availability, payment, shipping, and delivery details are not yet published.',
    contactNote: 'No contact details are displayed until the client verifies and approves them.',
    form: {
      heading: 'Your enquiry',
      name: 'Full Name',
      namePlaceholder: 'Your full name',
      mobile: 'Mobile Number',
      mobilePlaceholder: '10-digit Indian mobile number',
      email: 'Email Address',
      emailPlaceholder: 'name@example.com',
      city: 'City',
      cityPlaceholder: 'Your city',
      requirement: 'Requirement',
      requirementPlaceholder: 'Choose an option',
      requirementOptions: [
        ['success', 'Success Bracelet'],
        ['evil-eye', 'Evil Eye Protection Bracelet'],
        ['money-magnet', 'Money Magnet Bracelet'],
        ['pyrite', 'Pyrite Bracelet'],
        ['guidance', 'General Crystal Guidance'],
        ['ritual', '21-Day Ritual Information'],
      ],
      message: 'Message',
      messagePlaceholder: 'Share your question or the intention you would like to practise...',
      consent: 'I agree that my details may be used to respond to this enquiry.',
      submit: 'Submit enquiry',
      optional: 'Optional',
      privacy: 'This preview does not send, store, or log your information.',
      required: 'Please complete this required field.',
      mobileInvalid: 'Enter a valid 10-digit Indian mobile number.',
      emailInvalid: 'Enter a valid email address.',
      maxLength: 'Please shorten this response.',
      developmentNotice:
        'Secure submission will be enabled during backend integration. Your details were not sent or stored.',
    },
    imageFallback: 'Product image is temporarily unavailable.',
    footerStatement: 'Crystal bracelets, personal guidance, and a 21-day intention practice.',
    footerNavigation: 'Navigation',
    footerLegal: 'Legal',
    footerRights: 'All rights reserved.',
    backToTop: 'Back to top',
    skipLink: 'Skip to main content',
    cookieTitle: 'Your privacy matters',
    cookieBody: 'We use only essential storage for a reliable bilingual experience.',
    cookieAccept: 'Accept',
    cookieSettings: 'Preferences',
  },
  te: {
    locale: 'te',
    brandTagline: 'క్రిస్టల్స్ · ఉద్దేశం · సాధన',
    announcement:
      'అర్హత ఉన్న ప్రతి బ్రేస్‌లెట్ కొనుగోలుతో అదనపు ఫీజు లేకుండా అందించే 21-Day Crystal Ritual.',
    announcementCta: 'ఈ అనుభవం గురించి తెలుసుకోండి',
    announcementClose: 'ప్రకటనను మూసివేయండి',
    navLabel: 'ప్రధాన నావిగేషన్',
    mobileNavLabel: 'మొబైల్ నావిగేషన్',
    nav: [
      { label: 'హోమ్', href: '#home' },
      { label: 'కలెక్షన్', href: '#collection' },
      { label: '21-Day Ritual', href: '#ritual' },
      { label: 'మా గురించి', href: '#about' },
      { label: 'ప్రశ్నలు', href: '#faq' },
      { label: 'సంప్రదించండి', href: '#contact' },
    ],
    headerCta: 'కలెక్షన్ చూడండి',
    openMenu: 'మెనూ తెరవండి',
    closeMenu: 'మెనూ మూసివేయండి',
    mobileNote: 'మీ ఉద్దేశాన్ని ఎంచుకోండి, కలెక్షన్ చూడండి, నిర్ణయం ముందు ప్రశ్నలు అడగండి.',
    languageLabel: 'వెబ్‌సైట్ భాషను ఎంచుకోండి',
    englishSwitchLabel: 'వెబ్‌సైట్ భాషను ఆంగ్లంలోకి మార్చండి',
    teluguSwitchLabel: 'తెలుగు ఎంపిక చేయబడింది',
    studioLabel: 'వ్యక్తిగతమైన క్రిస్టల్ అనుభవం',
    heroTitle: 'మీ ఎనర్జీని మార్చుకోండి.',
    heroEmphasis: 'మీ జీవితంలో మార్పుకు అడుగు వేయండి.',
    heroSupporting:
      'Pratyusha వ్యక్తిగత మార్గదర్శనంతో జాగ్రత్తగా ఎంపిక చేసిన క్రిస్టల్ బ్రేస్‌లెట్లు. మైండ్‌ఫుల్‌నెస్, ఉద్దేశం, అఫర్మేషన్స్ మరియు క్రమంగా తీసుకునే ఆచరణాత్మక అడుగులపై దృష్టి పెట్టే, అదనపు ఫీజు లేకుండా అందించే 21-Day Crystal Ritual.',
    heroBody:
      'మీరు సాధన చేయాలనుకునే ఉద్దేశాన్ని గుర్తు చేసే బ్రేస్‌లెట్‌ను ఎంచుకోండి. తర్వాత దాన్ని రోజువారీ గుర్తుగా ఉపయోగిస్తూ, సులభమైన 21 రోజుల మార్గదర్శక సాధనను కొనసాగించండి.',
    heroPrimary: 'క్రిస్టల్ కలెక్షన్ చూడండి',
    heroSecondary: '21-Day Crystal Ritual గురించి తెలుసుకోండి',
    differentiatorTitle: 'మరింత వ్యక్తిగతమైన క్రిస్టల్ అనుభవం',
    differentiatorSupporting: 'బ్రేస్‌లెట్‌తో పాటు మార్గదర్శనం.',
    differentiatorBody:
      'ఈ అనుభవం ఒక బ్రేస్‌లెట్, మీరు ఎంచుకున్న ఉద్దేశం, క్రమమైన వ్యక్తిగత సాధన చుట్టూ రూపొందించబడింది.',
    differentiators: [
      'శ్రద్ధగా ఎంపిక చేసిన బ్రేస్‌లెట్లు',
      'Pratyusha వ్యక్తిగత మార్గదర్శనం',
      'అదనపు ఫీజు లేకుండా అందించే 21 రోజుల సాధన',
      'మైండ్‌ఫుల్‌నెస్, సానుకూల అలవాట్లు, ఆచరణాత్మక అడుగులు',
    ],
    challenge: {
      eyebrow: 'మీకు పరిచయమైన సవాలు',
      title: 'మీ ఉద్దేశం స్పష్టంగా ఉన్నా, క్రమంగా కొనసాగించడం కష్టంగా అనిపిస్తుందా?',
      supporting:
        'ఒక చిన్న రోజువారీ గుర్తు, ముఖ్యమైన విషయానికి మళ్లీ దృష్టి పెట్టడానికి తోడ్పడవచ్చు.',
      body: 'బిజీ జీవితం, ఎన్నో ప్రాధాన్యతలు, కొన్నిసార్లు వచ్చే సందేహాలు—ఇవి వ్యక్తిగత లేదా వృత్తిపరమైన లక్ష్యాలపై దృష్టి నిలుపుకోవడం కష్టంగా చేయవచ్చు. సులభమైన సాధన కాసేపు ఆగి, ఆలోచించి, తర్వాతి ఆచరణాత్మక అడుగును ఎంచుకోవడానికి స్థలం ఇస్తుంది.',
      bullets: [],
    },
    support: {
      eyebrow: 'క్రిస్టల్ సాధన తోడ్పాటు',
      title: 'మీ ఉద్దేశాన్ని గుర్తు చేసే రోజువారీ సహచరం',
      supporting:
        'క్రిస్టల్ సాధనను మైండ్‌ఫుల్‌నెస్, ఆలోచన, వ్యక్తిగత చర్యలకు తోడుగా ఉపయోగించవచ్చు.',
      body: 'బ్రేస్‌లెట్‌ను కాసేపు ఆగి, మీ ఉద్దేశాన్ని గుర్తు చేసుకుని, మీరు కొనసాగించాలనుకునే అలవాట్లపై మళ్లీ దృష్టి పెట్టే గుర్తుగా ఉపయోగించవచ్చు. ఇది ఖచ్చితమైన ఫలితాన్ని ఇవ్వదు. ఆలోచనను ఆచరణాత్మక అడుగులతో ఎంత క్రమంగా కలుపుతారో అదే ముఖ్యం.',
      bullets: [
        'ఉద్దేశాన్ని స్పష్టంగా గుర్తుంచుకోవడానికి తోడ్పడుతుంది',
        'సానుకూల అలవాట్లను ప్రోత్సహిస్తుంది',
        'ఎంచుకున్న లక్ష్యాలపై దృష్టి నిలుపుకోవడానికి సహాయపడవచ్చు',
        'మైండ్‌ఫుల్‌నెస్ లేదా సెల్ఫ్‌కేర్ సాధనలో భాగంగా ఉపయోగించవచ్చు',
      ],
    },
    collection: {
      eyebrow: 'సిగ్నేచర్ కలెక్షన్',
      title: 'సిగ్నేచర్ క్రిస్టల్ కలెక్షన్',
      supporting: 'మీరు సాధన చేయాలనుకునే ఉద్దేశాన్ని ప్రతిబింబించే బ్రేస్‌లెట్‌ను ఎంచుకోండి.',
      body: 'ప్రతి బ్రేస్‌లెట్‌ను మైండ్‌ఫుల్‌నెస్, సానుకూల అలవాట్లు, క్రమమైన వ్యక్తిగత చర్యలకు తోడుగా ఉండే గుర్తుగా చూపుతున్నాం. ప్రతి వ్యక్తి అనుభవం భిన్నంగా ఉండవచ్చు.',
      bullets: [],
    },
    products: [
      {
        id: 'success',
        nameEn: 'Success Bracelet',
        nameTe: 'సక్సెస్ బ్రేస్‌లెట్',
        supporting: 'మీ లక్ష్యాలు, వాటికి అవసరమైన చర్యలను గుర్తు చేసే రోజువారీ బ్రేస్‌లెట్.',
        body: 'ఆత్మవిశ్వాసం, ప్రేరణ, లక్ష్యంపై దృష్టి, సానుకూల ఆలోచనలను సాధన చేయాలనుకునే వారి కోసం రూపొందించబడింది. ఇది మీ ఉద్దేశాన్ని గుర్తు చేయవచ్చు; కెరీర్, వ్యాపారం, చదువు లేదా వ్యక్తిగత విజయాన్ని హామీ ఇవ్వదు.',
        points: ['ఆత్మవిశ్వాసం', 'ప్రేరణ', 'లక్ష్యంపై దృష్టి', 'సానుకూల అలవాట్లు'],
        cta: 'Success Bracelet గురించి అడగండి',
        ...PRODUCT_MEDIA.success,
      },
      {
        id: 'evil-eye',
        nameEn: 'Evil Eye Protection Bracelet',
        nameTe: 'ఈవిల్ ఐ ప్రొటెక్షన్ బ్రేస్‌లెట్',
        supporting:
          'ప్రశాంతత, సానుకూల హద్దులు, రోజువారీ ఆత్మవిశ్వాసాన్ని గుర్తు చేసే సాంప్రదాయ చిహ్నం.',
        body: 'Evil Eye చిహ్నంతో అనుబంధం ఉన్నవారు, మైండ్‌ఫుల్ హద్దులు మరియు అంతరంగ ప్రశాంతతను గుర్తు చేసుకోవాలనుకునే వారి కోసం ఇది ఉద్దేశించబడింది. ఉత్పత్తి పేరు సాంప్రదాయ భావనను సూచిస్తుంది; వ్యక్తులు, సంఘటనలు, ఎనర్జీ లేదా హానినుంచి పూర్తి రక్షణను హామీ ఇవ్వదు.',
        points: ['భావోద్వేగ సమతుల్యత', 'ప్రశాంతత', 'సానుకూల హద్దులు', 'వ్యక్తిగత ఆత్మవిశ్వాసం'],
        cta: 'Evil Eye Bracelet గురించి అడగండి',
        ...PRODUCT_MEDIA.evilEye,
      },
      {
        id: 'money-magnet',
        nameEn: 'Money Magnet Bracelet',
        nameTe: 'మనీ మ్యాగ్నెట్ బ్రేస్‌లెట్',
        supporting:
          'అవకాశాలను గమనించే దృక్పథాన్ని పెంచుకుని, ఆచరణాత్మక ఆర్థిక లక్ష్యాలపై దృష్టి పెట్టడానికి గుర్తుగా ఉపయోగించుకోవచ్చు.',
        body: 'అవకాశాలను గమనించడం, ఉద్దేశ్యపూర్వక ఆర్థిక అలవాట్లు, క్రమమైన చర్యలను సాధన చేయాలనుకునే పెద్దల కోసం రూపొందించబడింది. ఇది డబ్బు, ఆదాయం, పెట్టుబడి ఫలితం లేదా వ్యాపార విజయాన్ని హామీ ఇవ్వదు.',
        points: [
          'అవకాశాల దృక్పథం',
          'అవకాశాలపై అవగాహన',
          'ఆర్థిక ఉద్దేశాలు',
          'సానుకూల ఆర్థిక అలవాట్లు',
        ],
        cta: 'Money Magnet Bracelet గురించి అడగండి',
        ...PRODUCT_MEDIA.moneyMagnet,
      },
      {
        id: 'pyrite',
        nameEn: 'Pyrite Bracelet',
        nameTe: 'పైరైట్ బ్రేస్‌లెట్',
        supporting:
          'సాంప్రదాయంగా ఆత్మవిశ్వాసం, అభివృద్ధితో అనుబంధం ఉన్న బ్రేస్‌లెట్. ఇక్కడ చర్యపై దృష్టి పెట్టే గుర్తుగా ఉపయోగించబడుతుంది.',
        body: 'ఆత్మవిశ్వాసం, ప్రేరణ, నాయకత్వం, పనిపై దృష్టిని గుర్తు చేసుకోవాలనుకునే వ్యాపారులు మరియు వృత్తి నిపుణుల కోసం రూపొందించబడింది. సాంప్రదాయ భావనలు నమ్మకాలపై ఆధారపడినవి; అభివృద్ధి లేదా వృత్తిపరమైన ఫలితాలను హామీ ఇవ్వవు.',
        points: ['ఆత్మవిశ్వాసం', 'ప్రేరణ', 'నాయకత్వ దృక్పథం', 'పనిపై దృష్టి'],
        cta: 'Pyrite Bracelet గురించి అడగండి',
        ...PRODUCT_MEDIA.pyrite,
      },
    ],
    ritual: {
      eyebrow: 'అదనపు ఫీజు లేకుండా అందించే 21-Day Crystal Ritual',
      title: 'బ్రేస్‌లెట్‌తో పాటు మార్గదర్శనం',
      supporting:
        'మైండ్‌ఫుల్‌నెస్, ఉద్దేశం, అఫర్మేషన్స్, కృతజ్ఞత, క్రమమైన వ్యక్తిగత చర్యలపై దృష్టి పెట్టే 21 రోజుల సాధన.',
      body: 'మీరు ఎంచుకున్న ఉద్దేశం చుట్టూ సులభమైన రోజువారీ పద్ధతిని ఏర్పరచుకోవడానికి ఈ ప్రతిపాదిత రిచువల్ రూపొందించబడింది.',
      bullets: [
        'మీరు ఎంచుకున్న ఉద్దేశాన్ని మళ్లీ గుర్తు చేసుకోవడం',
        'అఫర్మేషన్స్, ఆలోచనను మైండ్‌ఫుల్ ప్రాంప్ట్స్‌గా ఉపయోగించడం',
        'కృతజ్ఞత, సానుకూల అలవాట్లను సాధన చేయడం',
        'ఆలోచనను క్రమమైన వ్యక్తిగత చర్యతో కలపడం',
      ],
    },
    ritualNote:
      'సురక్షిత ఆర్డరింగ్ ప్రారంభించే ముందు తుది అంశాలు, పంపే విధానం, షెడ్యూల్, యాక్సెస్, అర్హతను నిర్ధారిస్తాం.',
    audience: {
      eyebrow: 'ఎవరి కోసం',
      title: 'మరింత ఉద్దేశ్యపూర్వకమైన రోజువారీ సాధన కోరుకునేవారి కోసం',
      supporting:
        'మొదటిసారి ప్రారంభించేవారికి కూడా సులభం. ఆచరణాత్మక వ్యక్తిగత చర్యలకు తోడుగా రూపొందించబడింది.',
      body: 'కాసేపు ఆగి, ఆలోచించి, సానుకూల అలవాట్లతో అనుసంధానం కావడానికి ఒక సులభమైన గుర్తు కోరుకునేవారికి ఈ అనుభవం ఉపయోగపడవచ్చు.',
      bullets: [
        'ఉద్యోగులు మరియు వ్యాపార యజమానులు',
        'ఎంట్రప్రెన్యూర్స్ మరియు విద్యార్థులు',
        'గృహిణులు',
        'ఆధ్యాత్మిక సాధనపై ఆసక్తి ఉన్నవారు',
        'మైండ్‌ఫుల్‌నెస్ లేదా వ్యక్తిగత ఎదుగుదల సాధనను మొదలుపెడుతున్నవారు',
      ],
    },
    experienceDifference: {
      eyebrow: 'శ్రద్ధతో కూడిన ప్రత్యేకత',
      title: 'ఈ క్రిస్టల్ జర్నీ ప్రత్యేకత ఏమిటి?',
      supporting: 'ఒక బ్రేస్‌లెట్, ఒక గైడెడ్ రూటీన్, క్రమమైన సాధనపై దృష్టి.',
      body: 'బ్రేస్‌లెట్ చుట్టూ ఇచ్చే మార్గదర్శనమే ఈ అనుభవం ప్రత్యేకత. క్రిస్టల్ ఖచ్చితమైన ఫలితాన్ని ఇస్తుందని ఇది హామీ ఇవ్వదు.',
      bullets: [
        'శ్రద్ధగా ఎంపిక చేసిన బ్రేస్‌లెట్',
        'Pratyusha వ్యక్తిగత మార్గదర్శనం',
        'అదనపు ఫీజు లేకుండా అందించే 21 రోజుల సాధన',
        'గైడెడ్ ఉద్దేశం మరియు అఫర్మేషన్ కార్యకలాపాలు',
        'ఆలోచనను ఆచరణాత్మక చర్యలతో కలపడానికి ప్రోత్సాహం',
      ],
    },
    processEyebrow: 'ఇది ఎలా పనిచేస్తుంది',
    processTitle: 'మీ క్రిస్టల్ జర్నీ',
    processSupporting: 'ఒక ఉద్దేశాన్ని ఎంచుకోవడం నుంచి క్రమమైన సాధన వరకు.',
    process: [
      {
        number: '01',
        title: 'ఎంచుకోండి',
        text: 'కలెక్షన్ చూసి, మీరు సాధన చేయాలనుకునే ఉద్దేశాన్ని గుర్తించండి.',
      },
      {
        number: '02',
        title: 'నిర్ధారించండి',
        text: 'ప్రశ్నలు అడిగి, నిర్ధారించిన ఎంక్వైరీ విధానాన్ని ఉపయోగించండి.',
      },
      {
        number: '03',
        title: 'అందుకోండి',
        text: 'ఆమోదించిన కేర్ మరియు రిచువల్ సమాచారంతో బ్రేస్‌లెట్‌ను అందుకోండి.',
      },
      {
        number: '04',
        title: 'సాధన చేయండి',
        text: 'నిర్ధారించిన 21 రోజుల మార్గదర్శనాన్ని అనుసరించండి.',
      },
      {
        number: '05',
        title: 'కొనసాగించండి',
        text: 'ఉపయోగకరమైన అలవాట్లను క్రమమైన వ్యక్తిగత చర్యలతో ముందుకు తీసుకెళ్లండి.',
      },
    ],
    aboutEyebrow: 'Pratyusha గురించి',
    aboutTitle: 'Pratyusha నుంచి వ్యక్తిగత మార్గదర్శనం',
    aboutSupporting: 'క్రిస్టల్స్, ఉద్దేశం, క్రమమైన రోజువారీ సాధనపై శ్రద్ధతో కూడిన విధానం.',
    aboutBody:
      'బ్రేస్‌లెట్ కంటే ఎక్కువ మార్గదర్శనం కోరుకునేవారి కోసం Pratyusha ఈ అనుభవాన్ని రూపొందించారు. ఒక ఉద్దేశాన్ని ఎంచుకుని, 21 రోజుల క్రమమైన సాధనను కొనసాగించడంలో సహాయం చేయడం ఆమె ఉద్దేశించిన పాత్ర.',
    aboutBadge: 'వ్యక్తిగత మార్గదర్శనం',
    founderAlt: 'వెచ్చని ఇండోర్ వాతావరణంలో సాంప్రదాయ గులాబీ రంగు చీరలో Pratyusha',
    faqEyebrow: 'సాధారణ ప్రశ్నలు',
    faqTitle: 'ఎంచుకునే ముందు స్పష్టమైన సమాధానాలు',
    faqSupporting: 'సురక్షితంగా చెప్పగలిగిన వివరాలను మాత్రమే ఇక్కడ చూపుతున్నాం.',
    faqPrompt: 'ఇంకా ప్రశ్న ఉందా?',
    faqLink: 'వివరాలు పంపండి.',
    faqs: [
      {
        question: 'ఇంతకు ముందు ఆధ్యాత్మిక సాధన అనుభవం అవసరమా?',
        answer:
          'అవసరం లేదు. మొదటిసారి ప్రారంభించేవారికి కూడా ఇది సులభంగా ఉండేలా ఉద్దేశించబడింది. బ్రేస్‌లెట్‌ను వ్యక్తిగత గుర్తుగా, రిచువల్‌ను సులభమైన మైండ్‌ఫుల్‌నెస్ మరియు ఉద్దేశ సాధనగా చూడవచ్చు.',
      },
      {
        question: 'బ్రేస్‌లెట్‌ను ప్రతిరోజూ ధరించవచ్చా?',
        answer:
          'చాలామంది తమ ఉద్దేశాన్ని గుర్తు చేసుకోవడానికి బ్రేస్‌లెట్‌ను రోజూ ఉపయోగిస్తారు. తుది ధరింపు, కేర్ సూచనలు మెటీరియల్, తయారీ విధానం, నీటి ప్రభావం, చర్మ సున్నితత్వం వివరాలపై ఆధారపడతాయి.',
      },
      {
        question: '21-Day Ritualలో ఏమి జరుగుతుంది?',
        answer:
          'ప్రతిపాదిత అనుభవం ఉద్దేశం, అఫర్మేషన్స్, ఆలోచన, కృతజ్ఞత, సులభమైన రోజువారీ సాధనలపై దృష్టి పెడుతుంది. ఆర్డరింగ్ ప్రారంభించే ముందు తుది అంశాలు మరియు పంపే విధానాన్ని నిర్ధారిస్తాం.',
      },
    ],
    disclaimerTitle: 'క్రిస్టల్ మరియు వెల్‌నెస్ సాధనల గురించి ఒక గమనిక',
    disclaimerBody:
      'క్రిస్టల్ ఉత్పత్తులు మరియు 21-Day Crystal Ritualను మైండ్‌ఫుల్‌నెస్, ఉద్దేశం, ఆలోచన, వ్యక్తిగత వెల్‌నెస్ సాధనలకు తోడుగా ఉపయోగించవచ్చు. ఇవి వైద్య చికిత్సలు కావు. వైద్య, మానసిక, చట్టపరమైన లేదా ఆర్థిక నిపుణుల సలహాకు బదులు కావు. ప్రతి వ్యక్తి అనుభవం భిన్నంగా ఉండవచ్చు. డబ్బు, ఆరోగ్యం, సంబంధాలు, కెరీర్, వ్యాపారం లేదా రక్షణ విషయంలో ఎలాంటి ఖచ్చితమైన ఫలితాన్నీ ఇవి హామీ ఇవ్వవు. అవసరమైన ఆచరణాత్మక అడుగులు తీసుకుంటూ, అవసరమైనప్పుడు అర్హత కలిగిన నిపుణుల సహాయం పొందాలి.',
    conversionEyebrow: 'ఒక ఉద్దేశ్యపూర్వక అడుగుతో ప్రారంభించండి',
    conversionTitle: 'మీరు సాధన చేయాలనుకునే ఉద్దేశాన్ని గుర్తు చేసే బ్రేస్‌లెట్‌ను చూడండి.',
    conversionBody:
      'కలెక్షన్ చూడండి. ప్రతిపాదిత 21 రోజుల అనుభవం గురించి తెలుసుకోండి. నిర్ణయం తీసుకునే ముందు మీ ప్రశ్నలు అడగండి.',
    conversionCta: 'క్రిస్టల్ కలెక్షన్ చూడండి',
    contactEyebrow: 'ఎంక్వైరీ',
    contactTitle: 'బ్రేస్‌లెట్ గురించి అడగాలనుకుంటున్నారా?',
    contactSupporting: 'బ్రేస్‌లెట్ పేరు, మీ నగరం, మీ ప్రశ్నను పంచుకోండి.',
    contactBody:
      'బ్యాకెండ్ ఇంటిగ్రేషన్ సమయంలో సురక్షిత సబ్మిషన్ ప్రారంభిస్తాం. ధరలు, స్టాక్, చెల్లింపు, షిప్పింగ్, డెలివరీ వివరాలు ఇంకా ప్రచురించలేదు.',
    contactNote: 'క్లయింట్ నిర్ధారించి ఆమోదించిన తర్వాత మాత్రమే సంప్రదింపు వివరాలు చూపుతాం.',
    form: {
      heading: 'మీ ఎంక్వైరీ',
      name: 'పూర్తి పేరు',
      namePlaceholder: 'మీ పూర్తి పేరు',
      mobile: 'మొబైల్ నంబర్',
      mobilePlaceholder: '10 అంకెల భారతీయ మొబైల్ నంబర్',
      email: 'ఇమెయిల్ అడ్రస్',
      emailPlaceholder: 'name@example.com',
      city: 'నగరం',
      cityPlaceholder: 'మీ నగరం',
      requirement: 'మీ అవసరం',
      requirementPlaceholder: 'ఒక ఎంపికను ఎంచుకోండి',
      requirementOptions: [
        ['success', 'Success Bracelet / సక్సెస్ బ్రేస్‌లెట్'],
        ['evil-eye', 'Evil Eye Protection Bracelet / ఈవిల్ ఐ ప్రొటెక్షన్ బ్రేస్‌లెట్'],
        ['money-magnet', 'Money Magnet Bracelet / మనీ మ్యాగ్నెట్ బ్రేస్‌లెట్'],
        ['pyrite', 'Pyrite Bracelet / పైరైట్ బ్రేస్‌లెట్'],
        ['guidance', 'సాధారణ క్రిస్టల్ మార్గదర్శనం'],
        ['ritual', '21-Day Ritual సమాచారం'],
      ],
      message: 'సందేశం',
      messagePlaceholder: 'మీ ప్రశ్న లేదా మీరు సాధన చేయాలనుకునే ఉద్దేశాన్ని పంచుకోండి...',
      consent: 'ఈ ఎంక్వైరీకి సమాధానం ఇవ్వడానికి నా వివరాలను ఉపయోగించవచ్చని అంగీకరిస్తున్నాను.',
      submit: 'ఎంక్వైరీ పంపండి',
      optional: 'ఐచ్చికం',
      privacy: 'ఈ ప్రివ్యూ మీ సమాచారాన్ని పంపదు, నిల్వ చేయదు లేదా లాగ్ చేయదు.',
      required: 'దయచేసి ఈ అవసరమైన ఫీల్డ్‌ను పూర్తి చేయండి.',
      mobileInvalid: 'సరైన 10 అంకెల భారతీయ మొబైల్ నంబర్ నమోదు చేయండి.',
      emailInvalid: 'సరైన ఇమెయిల్ అడ్రస్ నమోదు చేయండి.',
      maxLength: 'దయచేసి ఈ సమాధానాన్ని కుదించండి.',
      developmentNotice:
        'బ్యాకెండ్ ఇంటిగ్రేషన్ సమయంలో సురక్షిత సబ్మిషన్ ప్రారంభిస్తాం. మీ వివరాలు పంపబడలేదు లేదా నిల్వ చేయబడలేదు.',
    },
    imageFallback: 'ఉత్పత్తి చిత్రం తాత్కాలికంగా అందుబాటులో లేదు.',
    footerStatement: 'క్రిస్టల్ బ్రేస్‌లెట్లు, వ్యక్తిగత మార్గదర్శనం, 21 రోజుల ఉద్దేశ సాధన.',
    footerNavigation: 'నావిగేషన్',
    footerLegal: 'లీగల్',
    footerRights: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    backToTop: 'పేజీ పైకి వెళ్లండి',
    skipLink: 'ప్రధాన కంటెంట్‌కు వెళ్లండి',
    cookieTitle: 'మీ గోప్యత ముఖ్యం',
    cookieBody: 'నమ్మకమైన ద్విభాషా అనుభవం కోసం అవసరమైన స్టోరేజ్‌ను మాత్రమే ఉపయోగిస్తాం.',
    cookieAccept: 'అంగీకరించండి',
    cookieSettings: 'ప్రాధాన్యతలు',
  },
};
